// Code generated by server_generator. DO NOT EDIT.
// generated version: devel

package interfaces

import (
	"io"
	"log"
	"net/http"

	"github.com/kurisuke5/api_gen_example/backend/interfaces/props"
	"github.com/kurisuke5/api_gen_example/backend/interfaces/wrapper"
	"github.com/labstack/echo/v4"
	"golang.org/x/xerrors"
)

// Routes ...
type Routes struct {
	router *echo.Group
}

// NewRoutes ...
func NewRoutes(p *props.ControllerProps, router *echo.Group, opts ...io.Writer) *Routes {
	if len(opts) > 0 {
		if w := opts[0]; w != nil {
			log.SetOutput(w)
		}
	}
	r := &Routes{
		router: router,
	}
	router.GET("health_check", r.GetHealthCheck(p))
	return r
}

// GetHealthCheck ...
func (r *Routes) GetHealthCheck(p *props.ControllerProps) echo.HandlerFunc {
	i := NewGetHealthCheckController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *GetHealthCheckRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(GetHealthCheckRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/health_check): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.GetHealthCheck(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// IGetHealthCheckController ...
type IGetHealthCheckController interface {
	GetHealthCheck(c echo.Context, req *GetHealthCheckRequest) (res *GetHealthCheckResponse, err error)
}
